# Travis file upgraded to stack at 2015-31-12 using template from
# <http://docs.haskellstack.org/en/stable/travis_ci.html>.
#
# Travis file initially created at 2015-05-31 using template from
# <https://github.com/hvr/multi-ghc-travis/commit/c9c87d36c450d7f9cb3183dcaf1f77b60f916f28>
# and taking the idea of using cabal-meta from yesodweb/yesod.

sudo: false
dist: trusty
language: c

services:
 - redis-server

addons:
  apt:
    packages:
    - libgmp-dev
  postgresql: "9.3"

cache:
  directories:
    - $HOME/.stack
    - .stack-work

matrix:
  include:
    # last 3 LTS and nightly
    - env: STACKARGS="--resolver=lts-8"
    - env: STACKARGS="--resolver=lts-9"
    - env: STACKARGS="--resolver=lts-10"
    - env: STACKARGS="--resolver=nightly"

before_install:
  # Download and unpack the stack executable
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

before_script:
  - psql -c "CREATE USER test WITH PASSWORD 'test';" -U postgres
  - psql -c "CREATE DATABASE test;" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE test TO test;" -U postgres

install:
  - stack setup $STACKARGS

script:
  - stack test --fast $STACKARGS serversession
  - stack test --fast $STACKARGS serversession-backend-acid-state
  - du -hcs serversession-backend-acid-state/state; rm -Rfv serversession-backend-acid-state/state
  - stack test --fast $STACKARGS serversession-backend-persistent --test-arguments='"--skip=100 MiB"'
  - du -hcs serversession-backend-persistent/test.db*; rm -Rfv serversession-backend-persistent/test.db*
  - psql -c 'SELECT COUNT(*) FROM "persistent_session";' -U test test; psql -c 'DROP DATABASE test;' -U postgres
  - stack test --fast $STACKARGS serversession-backend-redis
  - redis-cli FLUSHALL
  - stack test --fast $STACKARGS --no-run-tests # Make sure everything else builds
  - stack $STACKARGS sdist
